[tools]
argocd = "latest"
aws-cli = "latest"
bat = "latest"
chezmoi = "latest"
cilium-cli = "latest"
cosign = "latest"
fzf = "latest"
go = "latest"
helm = "latest"
helmfile = "latest"
k9s = "latest"
krew = "latest"
kubectl = "latest"
minikube = "latest"
neovim = "latest"
nim = "latest"
opentofu = "latest"
python = "3.13.5"
rclone = "latest"
ripgrep = "latest"
shellcheck = "latest"
starship = "latest"
terraform = "latest"
terraform-ls = "latest"
terragrunt = "latest"
usage = "latest"
uv = "latest"
zoxide = "latest"

[settings]
idiomatic_version_file_enable_tools = ["go"]

